// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2QRY8Hy29h31A3M5HImVX6UzHEU1aTvg',
    appId: '1:549975126563:web:e54cd746ebf3dc789e3796',
    messagingSenderId: '549975126563',
    projectId: 'todo-app-db685',
    authDomain: 'todo-app-db685.firebaseapp.com',
    storageBucket: 'todo-app-db685.firebasestorage.app',
    measurementId: 'G-HF7BY9VSB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW9V62QWEjNi1jUf-6gJGezi4jw81WV08',
    appId: '1:549975126563:android:a8546b19553132c79e3796',
    messagingSenderId: '549975126563',
    projectId: 'todo-app-db685',
    storageBucket: 'todo-app-db685.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDABVc9iv-q_zyFLXEoxhS2-T8OsWHdmn0',
    appId: '1:549975126563:ios:427d2fd25719b4ce9e3796',
    messagingSenderId: '549975126563',
    projectId: 'todo-app-db685',
    storageBucket: 'todo-app-db685.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDABVc9iv-q_zyFLXEoxhS2-T8OsWHdmn0',
    appId: '1:549975126563:ios:427d2fd25719b4ce9e3796',
    messagingSenderId: '549975126563',
    projectId: 'todo-app-db685',
    storageBucket: 'todo-app-db685.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2QRY8Hy29h31A3M5HImVX6UzHEU1aTvg',
    appId: '1:549975126563:web:68a50daad0f6bacc9e3796',
    messagingSenderId: '549975126563',
    projectId: 'todo-app-db685',
    authDomain: 'todo-app-db685.firebaseapp.com',
    storageBucket: 'todo-app-db685.firebasestorage.app',
    measurementId: 'G-PKJVW06CRJ',
  );
}
